name: pra_ct_i_eal_2 # Assuming this is the project name, you might need to adjust
description: A new Flutter project.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0 # Or latest version
  path_provider: ^2.1.1 # Or latest version
  file_picker: ^6.1.1 # Or latest version
  intl: ^0.18.1 # Or latest version
  path: ^1.8.3 # Or latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Or latest version

flutter:
  uses-material-design: true
